// Code generated by "stringer -type=DBType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DBType_Unknown-1]
	_ = x[DBType_MySQL-2]
	_ = x[DBType_PostgreSQL-3]
	_ = x[DBType_SQLServer-4]
	_ = x[DBType_Oracle-5]
}

const _DBType_name = "DBType_UnknownDBType_MySQLDBType_PostgreSQLDBType_SQLServerDBType_Oracle"

var _DBType_index = [...]uint8{0, 14, 26, 43, 59, 72}

func (i DBType) String() string {
	i -= 1
	if i < 0 || i >= DBType(len(_DBType_index)-1) {
		return "DBType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DBType_name[_DBType_index[i]:_DBType_index[i+1]]
}
