// Code generated by "stringer -type=DBType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DBTypeUnknown-1]
	_ = x[DBTypeMySQL-2]
	_ = x[DBTypePostgreSQL-3]
	_ = x[DBTypeSQLServer-4]
	_ = x[DBTypeOracle-5]
}

const _DBType_name = "DBTypeUnknownDBTypeMySQLDBTypePostgreSQLDBTypeSQLServerDBTypeOracle"

var _DBType_index = [...]uint8{0, 13, 24, 40, 55, 67}

func (i DBType) String() string {
	i -= 1
	if i < 0 || i >= DBType(len(_DBType_index)-1) {
		return "DBType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DBType_name[_DBType_index[i]:_DBType_index[i+1]]
}
