// Code generated by "stringer -type=SQLType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SQLTypeUnknown-1]
	_ = x[SQLTypeSelect-2]
	_ = x[SQLTypeInsert-3]
	_ = x[SQLTypeUpdate-4]
	_ = x[SQLTypeDelete-5]
	_ = x[SQLTypeSelectForUpdate-6]
	_ = x[SQLTypeReplace-7]
	_ = x[SQLTypeTruncate-8]
	_ = x[SQLTypeCreate-9]
	_ = x[SQLTypeDrop-10]
	_ = x[SQLTypeLoad-11]
	_ = x[SQLTypeMerge-12]
	_ = x[SQLTypeShow-13]
	_ = x[SQLTypeAlter-14]
	_ = x[SQLTypeRename-15]
	_ = x[SQLTypeDump-16]
	_ = x[SQLTypeDebug-17]
	_ = x[SQLTypeExplain-18]
	_ = x[SQLTypeDesc-19]
	_ = x[SQLTypeSet-20]
	_ = x[SQLTypeReload-21]
	_ = x[SQLTypeSelectUnion-22]
	_ = x[SQLTypeCreateTable-23]
	_ = x[SQLTypeDropTable-24]
	_ = x[SQLTypeAlterTable-25]
	_ = x[SQLTypeSelectFromUpdate-26]
	_ = x[SQLTypeMultiDelete-27]
	_ = x[SQLTypeMultiUpdate-28]
	_ = x[SQLTypeCreateIndex-29]
	_ = x[SQLTypeDropIndex-30]
}

const _SQLType_name = "SQLTypeUnknownSQLTypeSelectSQLTypeInsertSQLTypeUpdateSQLTypeDeleteSQLTypeSelectForUpdateSQLTypeReplaceSQLTypeTruncateSQLTypeCreateSQLTypeDropSQLTypeLoadSQLTypeMergeSQLTypeShowSQLTypeAlterSQLTypeRenameSQLTypeDumpSQLTypeDebugSQLTypeExplainSQLTypeDescSQLTypeSetSQLTypeReloadSQLTypeSelectUnionSQLTypeCreateTableSQLTypeDropTableSQLTypeAlterTableSQLTypeSelectFromUpdateSQLTypeMultiDeleteSQLTypeMultiUpdateSQLTypeCreateIndexSQLTypeDropIndex"

var _SQLType_index = [...]uint16{0, 14, 27, 40, 53, 66, 88, 102, 117, 130, 141, 152, 164, 175, 187, 200, 211, 223, 237, 248, 258, 271, 289, 307, 323, 340, 363, 381, 399, 417, 433}

func (i SQLType) String() string {
	i -= 1
	if i < 0 || i >= SQLType(len(_SQLType_index)-1) {
		return "SQLType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SQLType_name[_SQLType_index[i]:_SQLType_index[i+1]]
}
