name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

categories:
  - title: 'alignment/seata-java'
    labels:
      - 'alignment/seata-java'
  - title: 'bug'
    labels:
      - 'bug'
  - title: 'ci/cd'
    labels:
      - 'ci/cd'
  - title: 'coding'
    labels:
      - 'coding'
  - title: 'documentation'
    labels:
      - 'documentation'
  - title: 'enhancement'
    labels:
      - 'enhancement'
  - title: 'good first issue'
    labels:
      - 'good first issue'
  - title: 'integration'
    labels:
      - 'integration'
  - title: 'milestone'
    labels:
      - 'milestone'
  - title: 'module/at'
    labels:
      - 'module/at'
  - title: 'module/rm'
    labels:
      - 'module/rm'
  - title: 'module/saga'
    labels:
      - 'module/saga'
  - title: 'module/tcc'
    labels:
      - 'module/tcc'
  - title: 'module/tm'
    labels:
      - 'module/tm'
  - title: 'module/xa'
    labels:
      - 'module/xa'
  - title: 'optimise'
    labels:
      - 'optimise'
  - title: 'protocol'
    labels:
      - 'protocol'
  - title: 'question'
    labels:
      - 'question'
  - title: 'refactor'
    labels:
      - 'refactor'
  - title: 'remoting'
    labels:
      - 'remoting'
  - title: 'rm'
    labels:
      - 'rm'
  - title: 'task: help-wanted'
    labels:
      - 'task: help-wanted'
  - title: 'tm'
    labels:
      - 'tm'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'
exclude-contributors:
  - dependabot
  - dependabot[bot]

version-resolver:
  major:
    labels:
      - 'enhancement'
      - 'module/at'
  minor:
    labels:
      - 'enhancement'
      - 'module/saga'
  patch:
    labels:
      - 'bug'
      - 'documentation'
      - 'refactor'
  default: patch

template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  **Contributors**: $CONTRIBUTORS

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**'
    title:
      - '/(docs?|typo|doc:|\[doc\]|comment)/i'

  - label: 'bug'
    title:
      - '/(fix|bug|error|fail|correct|missing)/i'
      - '/(race|deadlock)/i'

  - label: 'enhancement'
    title:
      - '/(feat|feature|add|implement|create)/i'

  - label: 'refactor'
    title:
      - '/(refactor|cleanup|deprecate|remove|unused)/i'

  - label: 'ci/cd'
    files:
      - '.github/workflows/**'
    title:
      - '/(ci|cd|workflow|pipeline)/i'

  - label: 'coding'
    title:
      - '/(bump|upgrade|dependencies?)/i'
    files:
      - 'go.mod'
      - 'go.sum'

  - label: 'question'
    title:
      - '/(question|ask|inquiry)/i'

  - label: 'good first issue'
    title:
      - '/(good first issue|easy|beginner|help wanted)/i'

  - label: 'module/saga'
    title:
      - '/(saga)/i'

  - label: 'module/at'
    title:
      - '/(at)/i'
    
  - label: 'module/xa'
    title:
    - '/(xa)/i'