/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package models

// ContextAnalysisRequest represents a request for dynamic context analysis
type ContextAnalysisRequest struct {
	NeedDescription string `json:"need_description"` // Agent返回的需求描述
	UserContext     string `json:"user_context"`     // 用户的原始上下文（可选）
}

// AnalysisResult represents the AI analysis result
type AnalysisResult struct {
	RequiredSkills    []string `json:"required_skills,omitempty"`    // AI识别的关键技能
	ContextTags       []string `json:"context_tags,omitempty"`       // 相关标签
	SuggestedWorkflow string   `json:"suggested_workflow,omitempty"` // 建议工作流
}

// ContextAnalysisResponse represents the response from context analysis
type ContextAnalysisResponse struct {
	Success        bool            `json:"success"`
	Message        string          `json:"message"`
	MatchedSkills  []AgentSkill    `json:"matched_skills"`  // 匹配到的技能
	RouteResult    *RouteResult    `json:"route_result"`    // 路由结果
	AnalysisResult *AnalysisResult `json:"analysis_result"` // AI分析结果
}

// RouteResult represents the result of routing to an agent
type RouteResult struct {
	AgentURL      string      `json:"agent_url"`      // 目标Agent的URL
	SkillID       string      `json:"skill_id"`       // 匹配的技能ID
	SkillName     string      `json:"skill_name"`     // 匹配的技能名称
	AgentInfo     *AgentCard  `json:"agent_info"`     // 从Hub发现的完整Agent信息
	AgentResponse interface{} `json:"agent_response"` // Agent返回的结果（可选）
}

// SkillMatchQuery represents the JSON query generated by AI for skill matching
type SkillMatchQuery struct {
	Query    string            `json:"query"`              // 主要查询关键词
	Skills   []string          `json:"skills,omitempty"`   // 具体技能ID列表
	Tags     []string          `json:"tags,omitempty"`     // 相关标签
	Priority string            `json:"priority,omitempty"` // 优先级：accuracy/speed
	Metadata map[string]string `json:"metadata,omitempty"` // 额外元数据
}
