# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: http://github.com/golangci/golangci-lint
    rev: v1.42.1
    hooks:
    -   id: golangci-lint
