//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: sample/tcc/grpc/pb/tcc_grpc.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B string `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sample_tcc_grpc_pb_tcc_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_sample_tcc_grpc_pb_tcc_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *Params) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

var File_sample_tcc_grpc_pb_tcc_grpc_proto protoreflect.FileDescriptor

var file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x74, 0x63, 0x63, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x63, 0x63, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24,
	0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x62, 0x32, 0x48, 0x0a, 0x13, 0x54, 0x43, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x31, 0x12, 0x31, 0x0a, 0x08, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x07, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x32, 0x42,
	0x0a, 0x13, 0x54, 0x43, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x32, 0x12, 0x2b, 0x0a, 0x08, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x07, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2f, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2d, 0x67, 0x6f, 0x2f,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x74, 0x63, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDescOnce sync.Once
	file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDescData = file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDesc
)

func file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDescGZIP() []byte {
	file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDescOnce.Do(func() {
		file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDescData)
	})
	return file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDescData
}

var (
	file_sample_tcc_grpc_pb_tcc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
	file_sample_tcc_grpc_pb_tcc_grpc_proto_goTypes  = []interface{}{
		(*Params)(nil),               // 0: Params
		(*wrapperspb.BoolValue)(nil), // 1: google.protobuf.BoolValue
		(*anypb.Any)(nil),            // 2: google.protobuf.Any
	}
)

var file_sample_tcc_grpc_pb_tcc_grpc_proto_depIdxs = []int32{
	0, // 0: TCCServiceBusiness1.Remoting:input_type -> Params
	0, // 1: TCCServiceBusiness2.Remoting:input_type -> Params
	1, // 2: TCCServiceBusiness1.Remoting:output_type -> google.protobuf.BoolValue
	2, // 3: TCCServiceBusiness2.Remoting:output_type -> google.protobuf.Any
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sample_tcc_grpc_pb_tcc_grpc_proto_init() }
func file_sample_tcc_grpc_pb_tcc_grpc_proto_init() {
	if File_sample_tcc_grpc_pb_tcc_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sample_tcc_grpc_pb_tcc_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sample_tcc_grpc_pb_tcc_grpc_proto_goTypes,
		DependencyIndexes: file_sample_tcc_grpc_pb_tcc_grpc_proto_depIdxs,
		MessageInfos:      file_sample_tcc_grpc_pb_tcc_grpc_proto_msgTypes,
	}.Build()
	File_sample_tcc_grpc_pb_tcc_grpc_proto = out.File
	file_sample_tcc_grpc_pb_tcc_grpc_proto_rawDesc = nil
	file_sample_tcc_grpc_pb_tcc_grpc_proto_goTypes = nil
	file_sample_tcc_grpc_pb_tcc_grpc_proto_depIdxs = nil
}
