// Code generated by MockGen. DO NOT EDIT.
// Source: test_zookeeper_client.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	zk "github.com/go-zookeeper/zk"
	gomock "github.com/golang/mock/gomock"
)

// MockZkConnInterface is a mock of ZkConnInterface interface.
type MockZkConnInterface struct {
	ctrl     *gomock.Controller
	recorder *MockZkConnInterfaceMockRecorder
}

// MockZkConnInterfaceMockRecorder is the mock recorder for MockZkConnInterface.
type MockZkConnInterfaceMockRecorder struct {
	mock *MockZkConnInterface
}

// NewMockZkConnInterface creates a new mock instance.
func NewMockZkConnInterface(ctrl *gomock.Controller) *MockZkConnInterface {
	mock := &MockZkConnInterface{ctrl: ctrl}
	mock.recorder = &MockZkConnInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZkConnInterface) EXPECT() *MockZkConnInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockZkConnInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockZkConnInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockZkConnInterface)(nil).Close))
}

// Get mocks base method.
func (m *MockZkConnInterface) Get(path string) ([]byte, *zk.Stat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*zk.Stat)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockZkConnInterfaceMockRecorder) Get(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockZkConnInterface)(nil).Get), path)
}

// GetW mocks base method.
func (m *MockZkConnInterface) GetW(path string) ([]byte, *zk.Stat, <-chan zk.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetW", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*zk.Stat)
	ret2, _ := ret[2].(<-chan zk.Event)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetW indicates an expected call of GetW.
func (mr *MockZkConnInterfaceMockRecorder) GetW(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetW", reflect.TypeOf((*MockZkConnInterface)(nil).GetW), path)
}
