// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/seata/seata-go/pkg/discovery/mock (interfaces: NacosClient)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/nacos-group/nacos-sdk-go/v2/model"
	vo "github.com/nacos-group/nacos-sdk-go/v2/vo"
)

// MockNacosClient is a mock of NacosClient interface.
type MockNacosClient struct {
	ctrl     *gomock.Controller
	recorder *MockNacosClientMockRecorder
}

// MockNacosClientMockRecorder is the mock recorder for MockNacosClient.
type MockNacosClientMockRecorder struct {
	mock *MockNacosClient
}

// NewMockNacosClient creates a new mock instance.
func NewMockNacosClient(ctrl *gomock.Controller) *MockNacosClient {
	mock := &MockNacosClient{ctrl: ctrl}
	mock.recorder = &MockNacosClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNacosClient) EXPECT() *MockNacosClientMockRecorder {
	return m.recorder
}

// BatchRegisterInstance mocks base method.
func (m *MockNacosClient) BatchRegisterInstance(arg0 vo.BatchRegisterInstanceParam) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRegisterInstance", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchRegisterInstance indicates an expected call of BatchRegisterInstance.
func (mr *MockNacosClientMockRecorder) BatchRegisterInstance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRegisterInstance", reflect.TypeOf((*MockNacosClient)(nil).BatchRegisterInstance), arg0)
}

// CloseClient mocks base method.
func (m *MockNacosClient) CloseClient() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseClient")
}

// CloseClient indicates an expected call of CloseClient.
func (mr *MockNacosClientMockRecorder) CloseClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseClient", reflect.TypeOf((*MockNacosClient)(nil).CloseClient))
}

// DeregisterInstance mocks base method.
func (m *MockNacosClient) DeregisterInstance(arg0 vo.DeregisterInstanceParam) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeregisterInstance", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeregisterInstance indicates an expected call of DeregisterInstance.
func (mr *MockNacosClientMockRecorder) DeregisterInstance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeregisterInstance", reflect.TypeOf((*MockNacosClient)(nil).DeregisterInstance), arg0)
}

// GetAllServicesInfo mocks base method.
func (m *MockNacosClient) GetAllServicesInfo(arg0 vo.GetAllServiceInfoParam) (model.ServiceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllServicesInfo", arg0)
	ret0, _ := ret[0].(model.ServiceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllServicesInfo indicates an expected call of GetAllServicesInfo.
func (mr *MockNacosClientMockRecorder) GetAllServicesInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllServicesInfo", reflect.TypeOf((*MockNacosClient)(nil).GetAllServicesInfo), arg0)
}

// GetService mocks base method.
func (m *MockNacosClient) GetService(arg0 vo.GetServiceParam) (model.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", arg0)
	ret0, _ := ret[0].(model.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockNacosClientMockRecorder) GetService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockNacosClient)(nil).GetService), arg0)
}

// RegisterInstance mocks base method.
func (m *MockNacosClient) RegisterInstance(arg0 vo.RegisterInstanceParam) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterInstance", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterInstance indicates an expected call of RegisterInstance.
func (mr *MockNacosClientMockRecorder) RegisterInstance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterInstance", reflect.TypeOf((*MockNacosClient)(nil).RegisterInstance), arg0)
}

// SelectAllInstances mocks base method.
func (m *MockNacosClient) SelectAllInstances(arg0 vo.SelectAllInstancesParam) ([]model.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAllInstances", arg0)
	ret0, _ := ret[0].([]model.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAllInstances indicates an expected call of SelectAllInstances.
func (mr *MockNacosClientMockRecorder) SelectAllInstances(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAllInstances", reflect.TypeOf((*MockNacosClient)(nil).SelectAllInstances), arg0)
}

// SelectInstances mocks base method.
func (m *MockNacosClient) SelectInstances(arg0 vo.SelectInstancesParam) ([]model.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectInstances", arg0)
	ret0, _ := ret[0].([]model.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectInstances indicates an expected call of SelectInstances.
func (mr *MockNacosClientMockRecorder) SelectInstances(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectInstances", reflect.TypeOf((*MockNacosClient)(nil).SelectInstances), arg0)
}

// SelectOneHealthyInstance mocks base method.
func (m *MockNacosClient) SelectOneHealthyInstance(arg0 vo.SelectOneHealthInstanceParam) (*model.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectOneHealthyInstance", arg0)
	ret0, _ := ret[0].(*model.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectOneHealthyInstance indicates an expected call of SelectOneHealthyInstance.
func (mr *MockNacosClientMockRecorder) SelectOneHealthyInstance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectOneHealthyInstance", reflect.TypeOf((*MockNacosClient)(nil).SelectOneHealthyInstance), arg0)
}

// ServerHealthy mocks base method.
func (m *MockNacosClient) ServerHealthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerHealthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ServerHealthy indicates an expected call of ServerHealthy.
func (mr *MockNacosClientMockRecorder) ServerHealthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerHealthy", reflect.TypeOf((*MockNacosClient)(nil).ServerHealthy))
}

// Subscribe mocks base method.
func (m *MockNacosClient) Subscribe(arg0 *vo.SubscribeParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNacosClientMockRecorder) Subscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNacosClient)(nil).Subscribe), arg0)
}

// Unsubscribe mocks base method.
func (m *MockNacosClient) Unsubscribe(arg0 *vo.SubscribeParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockNacosClientMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockNacosClient)(nil).Unsubscribe), arg0)
}

// UpdateInstance mocks base method.
func (m *MockNacosClient) UpdateInstance(arg0 vo.UpdateInstanceParam) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstance", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstance indicates an expected call of UpdateInstance.
func (mr *MockNacosClientMockRecorder) UpdateInstance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstance", reflect.TypeOf((*MockNacosClient)(nil).UpdateInstance), arg0)
}
