package constant

const (
	VarNameProcessType                  string = "_ProcessType_"
	VarNameOperationName                string = "_operation_name_"
	OperationNameStart                  string = "start"
	VarNameAsyncCallback                string = "_async_callback_"
	VarNameStateMachineInst             string = "_current_statemachine_instance_"
	VarNameStateMachine                 string = "_current_statemachine_"
	VarNameStateMachineEngine           string = "_current_statemachine_engine_"
	VarNameStateMachineConfig           string = "_statemachine_config_"
	VarNameStateMachineContext          string = "context"
	VarNameIsAsyncExecution             string = "_is_async_execution_"
	VarNameStateInst                    string = "_current_state_instance_"
	SeqEntityStateMachineInst           string = "STATE_MACHINE_INST"
	VarNameBusinesskey                  string = "_business_key_"
	VarNameParentId                     string = "_parent_id_"
	StateTypeServiceTask                string = "ServiceTask"
	StateTypeChoice                     string = "Choice"
	StateTypeSubStateMachine            string = "SubStateMachine"
	CompensateSubMachine                string = "CompensateSubMachine"
	StateTypeSucceed                    string = "Succeed"
	StateTypeFail                       string = "Fail"
	StateTypeCompensationTrigger        string = "CompensationTrigger"
	StateTypeScriptTask                 string = "ScriptTask"
	CompensateSubMachineStateNamePrefix string = "_compensate_sub_machine_state_"
	DefaultScriptType                   string = "groovy"
)
