# test-provider Agent Configuration
# Generated on 2025-09-26 21:33:48

server:
  host: "0.0.0.0"
  port: 8080
  mode: "release"

agent:
  name: "test-provider"
  version: "1.0.0"
  description: "A default mode Go agent"

log:
  level: "info"
  format: "json"

skills:
  enabled:
    - "example"
