name: "🐞 Bug Report"
description: "Report a bug to help us improve"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 👋 Thank you for your feedback!
        
        Please fill out the following information to help us understand and resolve the issue.

  - type: checkboxes
    id: duplicate-check
    attributes:
      label: "✅ Verification Checklist"
      description: "Please verify that you've completed the following:"
      options:
        - label: "🔍 I have searched the [existing issues](https://github.com/apache/incubator-seata-go/issues) and confirmed this is not a duplicate"
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 🔧 Environment Information

  - type: input
    id: go-version
    attributes:
      label: "🚀 Go Version"
      description: "The version of Go you're using"
      placeholder: "e.g., 1.23.0"
    validations:
      required: true

  - type: input
    id: seata-go-version
    attributes:
      label: "📦 Seata-go Version"
      description: "The version of seata-go you're using"
      placeholder: "e.g: v1.2.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: "💾 Operating System"
      description: "What platform are you using?"
      options:
        - "🪟 Windows"
        - "🍎 macOS"
        - "🐧 Linux"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 🐛 Issue Details

  - type: textarea
    id: bug-description
    attributes:
      label: "📝 Bug Description"
      description: "A clear and concise description of what the bug is"
      placeholder: |
        Please describe the bug in detail, including:
        • Specific problem symptoms
        • Error messages (if any)
        • Impact scope
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "Please provide detailed steps to reproduce this issue"
      placeholder: |
        Please list the steps to reproduce:
        1. First step...
        2. Second step...
        3. Third step...
        4. See error

        💡 If possible, please provide a GitHub repository link or minimal reproduction code
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe in detail what the correct behavior should be..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "❌ Actual Behavior"
      description: "What actually happened?"
      placeholder: |
        Describe what actually happened, including:
        • Error messages
        • Exception stack traces
        • Log output
    validations:
      required: true

  - type: textarea
    id: possible-solution
    attributes:
      label: "💡 Possible Solution"
      description: "If you have ideas on how to fix this issue, please share them here"
      placeholder: "Share your thoughts, suggestions, or attempted solutions..."
    validations:
      required: false
