// Code generated by protoc-gen-go. DO NOT EDIT.
// source: undo_log.proto

package parser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PbSqlUndoLog struct {
	SqlType              int32           `protobuf:"varint,1,opt,name=SqlType,proto3" json:"SqlType,omitempty"`
	TableName            string          `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	BeforeImage          *PbTableRecords `protobuf:"bytes,3,opt,name=BeforeImage,proto3" json:"BeforeImage,omitempty"`
	AfterImage           *PbTableRecords `protobuf:"bytes,4,opt,name=AfterImage,proto3" json:"AfterImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PbSqlUndoLog) Reset()         { *m = PbSqlUndoLog{} }
func (m *PbSqlUndoLog) String() string { return proto.CompactTextString(m) }
func (*PbSqlUndoLog) ProtoMessage()    {}
func (*PbSqlUndoLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8c28d37170efce, []int{0}
}

func (m *PbSqlUndoLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbSqlUndoLog.Unmarshal(m, b)
}
func (m *PbSqlUndoLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbSqlUndoLog.Marshal(b, m, deterministic)
}
func (m *PbSqlUndoLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbSqlUndoLog.Merge(m, src)
}
func (m *PbSqlUndoLog) XXX_Size() int {
	return xxx_messageInfo_PbSqlUndoLog.Size(m)
}
func (m *PbSqlUndoLog) XXX_DiscardUnknown() {
	xxx_messageInfo_PbSqlUndoLog.DiscardUnknown(m)
}

var xxx_messageInfo_PbSqlUndoLog proto.InternalMessageInfo

func (m *PbSqlUndoLog) GetSqlType() int32 {
	if m != nil {
		return m.SqlType
	}
	return 0
}

func (m *PbSqlUndoLog) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *PbSqlUndoLog) GetBeforeImage() *PbTableRecords {
	if m != nil {
		return m.BeforeImage
	}
	return nil
}

func (m *PbSqlUndoLog) GetAfterImage() *PbTableRecords {
	if m != nil {
		return m.AfterImage
	}
	return nil
}

type PbBranchUndoLog struct {
	Xid                  string          `protobuf:"bytes,1,opt,name=Xid,proto3" json:"Xid,omitempty"`
	BranchId             int64           `protobuf:"varint,2,opt,name=BranchId,proto3" json:"BranchId,omitempty"`
	SqlUndoLogs          []*PbSqlUndoLog `protobuf:"bytes,3,rep,name=SqlUndoLogs,proto3" json:"SqlUndoLogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PbBranchUndoLog) Reset()         { *m = PbBranchUndoLog{} }
func (m *PbBranchUndoLog) String() string { return proto.CompactTextString(m) }
func (*PbBranchUndoLog) ProtoMessage()    {}
func (*PbBranchUndoLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8c28d37170efce, []int{1}
}

func (m *PbBranchUndoLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbBranchUndoLog.Unmarshal(m, b)
}
func (m *PbBranchUndoLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbBranchUndoLog.Marshal(b, m, deterministic)
}
func (m *PbBranchUndoLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbBranchUndoLog.Merge(m, src)
}
func (m *PbBranchUndoLog) XXX_Size() int {
	return xxx_messageInfo_PbBranchUndoLog.Size(m)
}
func (m *PbBranchUndoLog) XXX_DiscardUnknown() {
	xxx_messageInfo_PbBranchUndoLog.DiscardUnknown(m)
}

var xxx_messageInfo_PbBranchUndoLog proto.InternalMessageInfo

func (m *PbBranchUndoLog) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *PbBranchUndoLog) GetBranchId() int64 {
	if m != nil {
		return m.BranchId
	}
	return 0
}

func (m *PbBranchUndoLog) GetSqlUndoLogs() []*PbSqlUndoLog {
	if m != nil {
		return m.SqlUndoLogs
	}
	return nil
}

func init() {
	proto.RegisterType((*PbSqlUndoLog)(nil), "undo.PbSqlUndoLog")
	proto.RegisterType((*PbBranchUndoLog)(nil), "undo.PbBranchUndoLog")
}

func init() { proto.RegisterFile("undo_log.proto", fileDescriptor_5c8c28d37170efce) }

var fileDescriptor_5c8c28d37170efce = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xcd, 0x4b, 0xc9,
	0x8f, 0xcf, 0xc9, 0x4f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xf1, 0xa5, 0x84,
	0x4b, 0x12, 0x93, 0x72, 0x52, 0xe3, 0x8b, 0x52, 0x93, 0xf3, 0x8b, 0x52, 0x8a, 0x21, 0x52, 0x4a,
	0x5b, 0x18, 0xb9, 0x78, 0x02, 0x92, 0x82, 0x0b, 0x73, 0x42, 0xf3, 0x52, 0xf2, 0x7d, 0xf2, 0xd3,
	0x85, 0x24, 0xb8, 0xd8, 0x83, 0x0b, 0x73, 0x42, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x58, 0x83, 0x60, 0x5c, 0x21, 0x19, 0x2e, 0xce, 0x10, 0x90, 0x09, 0x7e, 0x89, 0xb9, 0xa9, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x21, 0x33, 0x2e, 0x6e, 0xa7, 0xd4, 0xb4, 0xfc,
	0xa2, 0x54, 0xcf, 0xdc, 0xc4, 0xf4, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x11, 0x3d,
	0x90, 0xcd, 0x7a, 0x01, 0x49, 0x60, 0x75, 0x41, 0x10, 0x9b, 0x83, 0x90, 0x15, 0x0a, 0x99, 0x70,
	0x71, 0x39, 0xa6, 0x95, 0xa4, 0x16, 0x41, 0xb4, 0xb1, 0xe0, 0xd1, 0x86, 0xa4, 0x4e, 0xa9, 0x94,
	0x8b, 0x3f, 0x20, 0xc9, 0xa9, 0x28, 0x31, 0x2f, 0x39, 0x03, 0xe6, 0x70, 0x01, 0x2e, 0xe6, 0x88,
	0xcc, 0x14, 0xb0, 0xa3, 0x39, 0x83, 0x40, 0x4c, 0x21, 0x29, 0x2e, 0x0e, 0x88, 0x12, 0xcf, 0x14,
	0xb0, 0x7b, 0x99, 0x83, 0xe0, 0x7c, 0x21, 0x13, 0x2e, 0x6e, 0x84, 0xa7, 0x8b, 0x25, 0x98, 0x15,
	0x98, 0x35, 0xb8, 0x8d, 0x84, 0x60, 0xf6, 0x22, 0xa4, 0x82, 0x90, 0x95, 0x25, 0xb1, 0x81, 0x03,
	0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x45, 0xe3, 0xc6, 0xf0, 0x61, 0x01, 0x00, 0x00,
}
