/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by "stringer -type=CompressorType"; DO NOT EDIT.

package compressor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompressorNone-0]
	_ = x[CompressorGzip-1]
	_ = x[CompressorZip-2]
	_ = x[CompressorSevenz-3]
	_ = x[CompressorBzip2-4]
	_ = x[CompressorLz4-5]
	_ = x[CompressorDefault-6]
	_ = x[CompressorZstd-7]
	_ = x[CompressorDeflate-8]
	_ = x[CompressorMaxl-9]
}

const _CompressorType_name = "CompressorNoneCompressorGzipCompressorZipCompressorSevenzCompressorBzip2CompressorLz4CompressorDefaultCompressorZstdCompressorDeflateCompressorMaxl"

var _CompressorType_index = [...]uint8{0, 14, 28, 41, 57, 72, 85, 102, 116, 133, 147}

func (i CompressorType) String() string {
	if i < 0 || i >= CompressorType(len(_CompressorType_index)-1) {
		return "CompressorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompressorType_name[_CompressorType_index[i]:_CompressorType_index[i+1]]
}
