/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by "stringer -type=CompressType"; DO NOT EDIT.

package compressor

import "strconv"

const _CompressType_name = "CompressGzipCompressZipCompressSevenzCompressBzip2CompressLz4CompressDeflateCompressZstdCompressMax"

var _CompressType_index = [...]uint8{0, 12, 23, 37, 50, 61, 76, 88, 99}

func (i CompressType) String() string {
	i -= 1
	if i < 0 || i >= CompressType(len(_CompressType_index)-1) {
		return "CompressType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CompressType_name[_CompressType_index[i]:_CompressType_index[i+1]]
}
