// Code generated by protoc-gen-go. DO NOT EDIT.
// source: table_records.proto

package parser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PbField struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	KeyType              int32    `protobuf:"varint,2,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
	Type                 int32    `protobuf:"zigzag32,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Value                []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbField) Reset()         { *m = PbField{} }
func (m *PbField) String() string { return proto.CompactTextString(m) }
func (*PbField) ProtoMessage()    {}
func (*PbField) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f74341eba9e488d, []int{0}
}

func (m *PbField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbField.Unmarshal(m, b)
}
func (m *PbField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbField.Marshal(b, m, deterministic)
}
func (m *PbField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbField.Merge(m, src)
}
func (m *PbField) XXX_Size() int {
	return xxx_messageInfo_PbField.Size(m)
}
func (m *PbField) XXX_DiscardUnknown() {
	xxx_messageInfo_PbField.DiscardUnknown(m)
}

var xxx_messageInfo_PbField proto.InternalMessageInfo

func (m *PbField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PbField) GetKeyType() int32 {
	if m != nil {
		return m.KeyType
	}
	return 0
}

func (m *PbField) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PbField) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PbRow struct {
	Fields               []*PbField `protobuf:"bytes,1,rep,name=Fields,proto3" json:"Fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PbRow) Reset()         { *m = PbRow{} }
func (m *PbRow) String() string { return proto.CompactTextString(m) }
func (*PbRow) ProtoMessage()    {}
func (*PbRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f74341eba9e488d, []int{1}
}

func (m *PbRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbRow.Unmarshal(m, b)
}
func (m *PbRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbRow.Marshal(b, m, deterministic)
}
func (m *PbRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbRow.Merge(m, src)
}
func (m *PbRow) XXX_Size() int {
	return xxx_messageInfo_PbRow.Size(m)
}
func (m *PbRow) XXX_DiscardUnknown() {
	xxx_messageInfo_PbRow.DiscardUnknown(m)
}

var xxx_messageInfo_PbRow proto.InternalMessageInfo

func (m *PbRow) GetFields() []*PbField {
	if m != nil {
		return m.Fields
	}
	return nil
}

type PbTableRecords struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Columns              []string `protobuf:"bytes,2,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Rows                 []*PbRow `protobuf:"bytes,3,rep,name=Rows,proto3" json:"Rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbTableRecords) Reset()         { *m = PbTableRecords{} }
func (m *PbTableRecords) String() string { return proto.CompactTextString(m) }
func (*PbTableRecords) ProtoMessage()    {}
func (*PbTableRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f74341eba9e488d, []int{2}
}

func (m *PbTableRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbTableRecords.Unmarshal(m, b)
}
func (m *PbTableRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbTableRecords.Marshal(b, m, deterministic)
}
func (m *PbTableRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbTableRecords.Merge(m, src)
}
func (m *PbTableRecords) XXX_Size() int {
	return xxx_messageInfo_PbTableRecords.Size(m)
}
func (m *PbTableRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_PbTableRecords.DiscardUnknown(m)
}

var xxx_messageInfo_PbTableRecords proto.InternalMessageInfo

func (m *PbTableRecords) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *PbTableRecords) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *PbTableRecords) GetRows() []*PbRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*PbField)(nil), "undo.PbField")
	proto.RegisterType((*PbRow)(nil), "undo.PbRow")
	proto.RegisterType((*PbTableRecords)(nil), "undo.PbTableRecords")
}

func init() { proto.RegisterFile("table_records.proto", fileDescriptor_0f74341eba9e488d) }

var fileDescriptor_0f74341eba9e488d = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x40, 0xd9, 0x26, 0x69, 0xc9, 0x54, 0x05, 0x47, 0x0f, 0x7b, 0x10, 0x5c, 0x02, 0xc2, 0x9e,
	0x72, 0xd0, 0x4f, 0x10, 0xbc, 0x08, 0x12, 0x86, 0xe2, 0x55, 0x76, 0xcd, 0x1e, 0x0a, 0xdb, 0x4e,
	0xc9, 0x36, 0x84, 0xfe, 0xbd, 0xec, 0xb4, 0xc1, 0xde, 0xe6, 0xcd, 0x2c, 0xbc, 0xc7, 0xc2, 0xc3,
	0xd1, 0xf9, 0x18, 0x7e, 0x86, 0xf0, 0xcb, 0x43, 0x9f, 0xda, 0xc3, 0xc0, 0x47, 0xc6, 0x72, 0xdc,
	0xf7, 0xdc, 0x38, 0x58, 0x75, 0xfe, 0x63, 0x1b, 0x62, 0x8f, 0x08, 0xe5, 0x97, 0xdb, 0x05, 0xad,
	0x8c, 0xb2, 0x35, 0xc9, 0x8c, 0x1a, 0x56, 0x9f, 0xe1, 0xb4, 0x39, 0x1d, 0x82, 0x5e, 0x18, 0x65,
	0x2b, 0x9a, 0x31, 0xbf, 0x96, 0x75, 0x61, 0x94, 0xbd, 0x27, 0x99, 0xf1, 0x11, 0xaa, 0x6f, 0x17,
	0xc7, 0xa0, 0x4b, 0xa3, 0xec, 0x0d, 0x9d, 0xa1, 0x69, 0xa1, 0xea, 0x3c, 0xf1, 0x84, 0x2f, 0xb0,
	0x14, 0x53, 0xd2, 0xca, 0x14, 0x76, 0xfd, 0x7a, 0xdb, 0xe6, 0x84, 0xf6, 0xe2, 0xa7, 0xcb, 0xb1,
	0xd9, 0xc2, 0x5d, 0xe7, 0x37, 0xb9, 0x98, 0xce, 0xc1, 0xf8, 0x04, 0xb5, 0xf0, 0x55, 0xde, 0xff,
	0x22, 0x37, 0xbe, 0x73, 0x1c, 0x77, 0xfb, 0xa4, 0x17, 0xa6, 0xb0, 0x35, 0xcd, 0x88, 0xcf, 0x50,
	0x12, 0x4f, 0x49, 0x17, 0xa2, 0x5b, 0xcf, 0x3a, 0xe2, 0x89, 0xe4, 0xe0, 0x97, 0xf2, 0x15, 0x6f,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xea, 0x28, 0xe4, 0xf3, 0x21, 0x01, 0x00, 0x00,
}
