// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: pkg/integration/grpc/pb/context_test.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContextRpcClient is the client API for ContextRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContextRpcClient interface {
	ContextRpc(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type contextRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewContextRpcClient(cc grpc.ClientConnInterface) ContextRpcClient {
	return &contextRpcClient{cc}
}

func (c *contextRpcClient) ContextRpc(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ContextRpc/ContextRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContextRpcServer is the server API for ContextRpc service.
// All implementations must embed UnimplementedContextRpcServer
// for forward compatibility
type ContextRpcServer interface {
	ContextRpc(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedContextRpcServer()
}

// UnimplementedContextRpcServer must be embedded to have forward compatible implementations.
type UnimplementedContextRpcServer struct {
}

func (UnimplementedContextRpcServer) ContextRpc(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContextRpc not implemented")
}
func (UnimplementedContextRpcServer) mustEmbedUnimplementedContextRpcServer() {}

// UnsafeContextRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContextRpcServer will
// result in compilation errors.
type UnsafeContextRpcServer interface {
	mustEmbedUnimplementedContextRpcServer()
}

func RegisterContextRpcServer(s grpc.ServiceRegistrar, srv ContextRpcServer) {
	s.RegisterService(&ContextRpc_ServiceDesc, srv)
}

func _ContextRpc_ContextRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextRpcServer).ContextRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContextRpc/ContextRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextRpcServer).ContextRpc(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ContextRpc_ServiceDesc is the grpc.ServiceDesc for ContextRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContextRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ContextRpc",
	HandlerType: (*ContextRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContextRpc",
			Handler:    _ContextRpc_ContextRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/integration/grpc/pb/context_test.proto",
}
