//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v6.30.2
// source: globalStatus.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishRequest is a publish request.
type GlobalStatusProto int32

const (
	// Unknown
	GlobalStatusProto_UnKnown GlobalStatusProto = 0
	// PHASE 1: can accept new branch registering.
	GlobalStatusProto_Begin GlobalStatusProto = 1
	// Committing.
	GlobalStatusProto_Committing GlobalStatusProto = 2
	// Retrying commit after a recoverable failure.
	GlobalStatusProto_CommitRetrying GlobalStatusProto = 3
	// Rollbacking
	GlobalStatusProto_Rollbacking GlobalStatusProto = 4
	// Retrying rollback after a recoverable failure.
	GlobalStatusProto_RollbackRetrying GlobalStatusProto = 5
	// Rollbacking since timeout
	GlobalStatusProto_TimeoutRollbacking GlobalStatusProto = 6
	// Retrying rollback (since timeout) after a recoverable failure.
	GlobalStatusProto_TimeoutRollbackRetrying GlobalStatusProto = 7
	// *
	// All branches can be async committed. The committing is NOT done yet, but it can be seen as committed for TM/RM
	// client.
	GlobalStatusProto_AsyncCommitting GlobalStatusProto = 8
	// Finally: global transaction is successfully committed.
	GlobalStatusProto_Committed GlobalStatusProto = 9
	// Finally: failed to commit
	GlobalStatusProto_CommitFailed GlobalStatusProto = 10
	// Finally: global transaction is successfully rollbacked.
	GlobalStatusProto_Rollbacked GlobalStatusProto = 11
	// Finally: failed to rollback
	GlobalStatusProto_RollbackFailed GlobalStatusProto = 12
	// Finally: global transaction is successfully rollbacked since timeout.
	GlobalStatusProto_TimeoutRollbacked GlobalStatusProto = 13
	// Finally: failed to rollback since timeout
	GlobalStatusProto_TimeoutRollbackFailed GlobalStatusProto = 14
	// Not managed in session MAP any more
	GlobalStatusProto_Finished GlobalStatusProto = 15
)

// Enum value maps for GlobalStatusProto.
var (
	GlobalStatusProto_name = map[int32]string{
		0:  "UnKnown",
		1:  "Begin",
		2:  "Committing",
		3:  "CommitRetrying",
		4:  "Rollbacking",
		5:  "RollbackRetrying",
		6:  "TimeoutRollbacking",
		7:  "TimeoutRollbackRetrying",
		8:  "AsyncCommitting",
		9:  "Committed",
		10: "CommitFailed",
		11: "Rollbacked",
		12: "RollbackFailed",
		13: "TimeoutRollbacked",
		14: "TimeoutRollbackFailed",
		15: "Finished",
	}
	GlobalStatusProto_value = map[string]int32{
		"UnKnown":                 0,
		"Begin":                   1,
		"Committing":              2,
		"CommitRetrying":          3,
		"Rollbacking":             4,
		"RollbackRetrying":        5,
		"TimeoutRollbacking":      6,
		"TimeoutRollbackRetrying": 7,
		"AsyncCommitting":         8,
		"Committed":               9,
		"CommitFailed":            10,
		"Rollbacked":              11,
		"RollbackFailed":          12,
		"TimeoutRollbacked":       13,
		"TimeoutRollbackFailed":   14,
		"Finished":                15,
	}
)

func (x GlobalStatusProto) Enum() *GlobalStatusProto {
	p := new(GlobalStatusProto)
	*p = x
	return p
}

func (x GlobalStatusProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalStatusProto) Descriptor() protoreflect.EnumDescriptor {
	return file_globalStatus_proto_enumTypes[0].Descriptor()
}

func (GlobalStatusProto) Type() protoreflect.EnumType {
	return &file_globalStatus_proto_enumTypes[0]
}

func (x GlobalStatusProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalStatusProto.Descriptor instead.
func (GlobalStatusProto) EnumDescriptor() ([]byte, []int) {
	return file_globalStatus_proto_rawDescGZIP(), []int{0}
}

var File_globalStatus_proto protoreflect.FileDescriptor

var file_globalStatus_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2a, 0xc5, 0x02, 0x0a, 0x11, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42,
	0x65, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x74, 0x72, 0x79, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x6f,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x52,
	0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x74, 0x72, 0x79, 0x69, 0x6e, 0x67, 0x10,
	0x05, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x6f, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x10, 0x06, 0x12, 0x1b, 0x0a, 0x17, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x74, 0x72,
	0x79, 0x69, 0x6e, 0x67, 0x10, 0x07, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x10, 0x09, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x0a, 0x12, 0x0e, 0x0a, 0x0a,
	0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x10, 0x0b, 0x12, 0x12, 0x0a, 0x0e,
	0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x0c,
	0x12, 0x15, 0x0a, 0x11, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x6f, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x64, 0x10, 0x0d, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x10, 0x0e, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x10, 0x0f,
	0x42, 0x30, 0x5a, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_globalStatus_proto_rawDescOnce sync.Once
	file_globalStatus_proto_rawDescData = file_globalStatus_proto_rawDesc
)

func file_globalStatus_proto_rawDescGZIP() []byte {
	file_globalStatus_proto_rawDescOnce.Do(func() {
		file_globalStatus_proto_rawDescData = protoimpl.X.CompressGZIP(file_globalStatus_proto_rawDescData)
	})
	return file_globalStatus_proto_rawDescData
}

var file_globalStatus_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_globalStatus_proto_goTypes = []interface{}{
	(GlobalStatusProto)(0), // 0: org.apache.seata.protocol.protobuf.GlobalStatusProto
}
var file_globalStatus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_globalStatus_proto_init() }
func file_globalStatus_proto_init() {
	if File_globalStatus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_globalStatus_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_globalStatus_proto_goTypes,
		DependencyIndexes: file_globalStatus_proto_depIdxs,
		EnumInfos:         file_globalStatus_proto_enumTypes,
	}.Build()
	File_globalStatus_proto = out.File
	file_globalStatus_proto_rawDesc = nil
	file_globalStatus_proto_goTypes = nil
	file_globalStatus_proto_depIdxs = nil
}
