//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v6.30.2
// source: globalReportRequest.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalReportRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbstractGlobalEndRequest *AbstractGlobalEndRequestProto `protobuf:"bytes,1,opt,name=abstractGlobalEndRequest,proto3" json:"abstractGlobalEndRequest,omitempty"`
	GlobalStatus             GlobalStatusProto              `protobuf:"varint,2,opt,name=globalStatus,proto3,enum=org.apache.seata.protocol.protobuf.GlobalStatusProto" json:"globalStatus,omitempty"`
}

func (x *GlobalReportRequestProto) Reset() {
	*x = GlobalReportRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_globalReportRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalReportRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalReportRequestProto) ProtoMessage() {}

func (x *GlobalReportRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_globalReportRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalReportRequestProto.ProtoReflect.Descriptor instead.
func (*GlobalReportRequestProto) Descriptor() ([]byte, []int) {
	return file_globalReportRequest_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalReportRequestProto) GetAbstractGlobalEndRequest() *AbstractGlobalEndRequestProto {
	if x != nil {
		return x.AbstractGlobalEndRequest
	}
	return nil
}

func (x *GlobalReportRequestProto) GetGlobalStatus() GlobalStatusProto {
	if x != nil {
		return x.GlobalStatus
	}
	return GlobalStatusProto_UnKnown
}

var File_globalReportRequest_proto protoreflect.FileDescriptor

var file_globalReportRequest_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x6f, 0x72, 0x67,
	0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a,
	0x1e, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf4, 0x01, 0x0a, 0x18, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x7d, 0x0a, 0x18, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x41, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x18, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x59, 0x0a, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x35, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0c, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x30, 0x5a, 0x2e, 0x73, 0x65,
	0x61, 0x74, 0x61, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x73,
	0x65, 0x61, 0x74, 0x61, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_globalReportRequest_proto_rawDescOnce sync.Once
	file_globalReportRequest_proto_rawDescData = file_globalReportRequest_proto_rawDesc
)

func file_globalReportRequest_proto_rawDescGZIP() []byte {
	file_globalReportRequest_proto_rawDescOnce.Do(func() {
		file_globalReportRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_globalReportRequest_proto_rawDescData)
	})
	return file_globalReportRequest_proto_rawDescData
}

var file_globalReportRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_globalReportRequest_proto_goTypes = []interface{}{
	(*GlobalReportRequestProto)(nil),      // 0: org.apache.seata.protocol.protobuf.GlobalReportRequestProto
	(*AbstractGlobalEndRequestProto)(nil), // 1: org.apache.seata.protocol.protobuf.AbstractGlobalEndRequestProto
	(GlobalStatusProto)(0),                // 2: org.apache.seata.protocol.protobuf.GlobalStatusProto
}
var file_globalReportRequest_proto_depIdxs = []int32{
	1, // 0: org.apache.seata.protocol.protobuf.GlobalReportRequestProto.abstractGlobalEndRequest:type_name -> org.apache.seata.protocol.protobuf.AbstractGlobalEndRequestProto
	2, // 1: org.apache.seata.protocol.protobuf.GlobalReportRequestProto.globalStatus:type_name -> org.apache.seata.protocol.protobuf.GlobalStatusProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_globalReportRequest_proto_init() }
func file_globalReportRequest_proto_init() {
	if File_globalReportRequest_proto != nil {
		return
	}
	file_abstractGlobalEndRequest_proto_init()
	file_globalStatus_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_globalReportRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalReportRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_globalReportRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_globalReportRequest_proto_goTypes,
		DependencyIndexes: file_globalReportRequest_proto_depIdxs,
		MessageInfos:      file_globalReportRequest_proto_msgTypes,
	}.Build()
	File_globalReportRequest_proto = out.File
	file_globalReportRequest_proto_rawDesc = nil
	file_globalReportRequest_proto_goTypes = nil
	file_globalReportRequest_proto_depIdxs = nil
}
