//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v6.30.2
// source: globalLockQueryRequest.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalLockQueryRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BranchRegisterRequest *BranchRegisterRequestProto `protobuf:"bytes,1,opt,name=branchRegisterRequest,proto3" json:"branchRegisterRequest,omitempty"`
}

func (x *GlobalLockQueryRequestProto) Reset() {
	*x = GlobalLockQueryRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_globalLockQueryRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalLockQueryRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalLockQueryRequestProto) ProtoMessage() {}

func (x *GlobalLockQueryRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_globalLockQueryRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalLockQueryRequestProto.ProtoReflect.Descriptor instead.
func (*GlobalLockQueryRequestProto) Descriptor() ([]byte, []int) {
	return file_globalLockQueryRequest_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalLockQueryRequestProto) GetBranchRegisterRequest() *BranchRegisterRequestProto {
	if x != nil {
		return x.BranchRegisterRequest
	}
	return nil
}

var File_globalLockQueryRequest_proto protoreflect.FileDescriptor

var file_globalLockQueryRequest_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4c, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22,
	0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x1a, 0x1b, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x93, 0x01, 0x0a, 0x1b, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4c, 0x6f, 0x63, 0x6b, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x74, 0x0a, 0x15, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3e,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x15,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x30, 0x5a, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x61,
	0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2d,
	0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_globalLockQueryRequest_proto_rawDescOnce sync.Once
	file_globalLockQueryRequest_proto_rawDescData = file_globalLockQueryRequest_proto_rawDesc
)

func file_globalLockQueryRequest_proto_rawDescGZIP() []byte {
	file_globalLockQueryRequest_proto_rawDescOnce.Do(func() {
		file_globalLockQueryRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_globalLockQueryRequest_proto_rawDescData)
	})
	return file_globalLockQueryRequest_proto_rawDescData
}

var file_globalLockQueryRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_globalLockQueryRequest_proto_goTypes = []interface{}{
	(*GlobalLockQueryRequestProto)(nil), // 0: org.apache.seata.protocol.protobuf.GlobalLockQueryRequestProto
	(*BranchRegisterRequestProto)(nil),  // 1: org.apache.seata.protocol.protobuf.BranchRegisterRequestProto
}
var file_globalLockQueryRequest_proto_depIdxs = []int32{
	1, // 0: org.apache.seata.protocol.protobuf.GlobalLockQueryRequestProto.branchRegisterRequest:type_name -> org.apache.seata.protocol.protobuf.BranchRegisterRequestProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_globalLockQueryRequest_proto_init() }
func file_globalLockQueryRequest_proto_init() {
	if File_globalLockQueryRequest_proto != nil {
		return
	}
	file_branchRegisterRequest_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_globalLockQueryRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalLockQueryRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_globalLockQueryRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_globalLockQueryRequest_proto_goTypes,
		DependencyIndexes: file_globalLockQueryRequest_proto_depIdxs,
		MessageInfos:      file_globalLockQueryRequest_proto_msgTypes,
	}.Build()
	File_globalLockQueryRequest_proto = out.File
	file_globalLockQueryRequest_proto_rawDesc = nil
	file_globalLockQueryRequest_proto_goTypes = nil
	file_globalLockQueryRequest_proto_depIdxs = nil
}
