//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v6.30.2
// source: registerTMResponse.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishRequest is a publish request.
type RegisterTMResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbstractIdentifyResponse *AbstractIdentifyResponseProto `protobuf:"bytes,1,opt,name=abstractIdentifyResponse,proto3" json:"abstractIdentifyResponse,omitempty"`
}

func (x *RegisterTMResponseProto) Reset() {
	*x = RegisterTMResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registerTMResponse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTMResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTMResponseProto) ProtoMessage() {}

func (x *RegisterTMResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_registerTMResponse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTMResponseProto.ProtoReflect.Descriptor instead.
func (*RegisterTMResponseProto) Descriptor() ([]byte, []int) {
	return file_registerTMResponse_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTMResponseProto) GetAbstractIdentifyResponse() *AbstractIdentifyResponseProto {
	if x != nil {
		return x.AbstractIdentifyResponse
	}
	return nil
}

var File_registerTMResponse_proto protoreflect.FileDescriptor

var file_registerTMResponse_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x4d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x6f, 0x72, 0x67, 0x2e,
	0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x1e,
	0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98,
	0x01, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x4d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x7d, 0x0a, 0x18, 0x61, 0x62,
	0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x18, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x73, 0x65, 0x61,
	0x74, 0x61, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x73, 0x65,
	0x61, 0x74, 0x61, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_registerTMResponse_proto_rawDescOnce sync.Once
	file_registerTMResponse_proto_rawDescData = file_registerTMResponse_proto_rawDesc
)

func file_registerTMResponse_proto_rawDescGZIP() []byte {
	file_registerTMResponse_proto_rawDescOnce.Do(func() {
		file_registerTMResponse_proto_rawDescData = protoimpl.X.CompressGZIP(file_registerTMResponse_proto_rawDescData)
	})
	return file_registerTMResponse_proto_rawDescData
}

var file_registerTMResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_registerTMResponse_proto_goTypes = []interface{}{
	(*RegisterTMResponseProto)(nil),       // 0: org.apache.seata.protocol.protobuf.RegisterTMResponseProto
	(*AbstractIdentifyResponseProto)(nil), // 1: org.apache.seata.protocol.protobuf.AbstractIdentifyResponseProto
}
var file_registerTMResponse_proto_depIdxs = []int32{
	1, // 0: org.apache.seata.protocol.protobuf.RegisterTMResponseProto.abstractIdentifyResponse:type_name -> org.apache.seata.protocol.protobuf.AbstractIdentifyResponseProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_registerTMResponse_proto_init() }
func file_registerTMResponse_proto_init() {
	if File_registerTMResponse_proto != nil {
		return
	}
	file_abstractIdentifyResponse_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_registerTMResponse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTMResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_registerTMResponse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registerTMResponse_proto_goTypes,
		DependencyIndexes: file_registerTMResponse_proto_depIdxs,
		MessageInfos:      file_registerTMResponse_proto_msgTypes,
	}.Build()
	File_registerTMResponse_proto = out.File
	file_registerTMResponse_proto_rawDesc = nil
	file_registerTMResponse_proto_goTypes = nil
	file_registerTMResponse_proto_depIdxs = nil
}
