//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v6.30.2
// source: resultCode.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishRequest is a publish request.
type ResultCodeProto int32

const (
	ResultCodeProto_Failed  ResultCodeProto = 0
	ResultCodeProto_Success ResultCodeProto = 1
)

// Enum value maps for ResultCodeProto.
var (
	ResultCodeProto_name = map[int32]string{
		0: "Failed",
		1: "Success",
	}
	ResultCodeProto_value = map[string]int32{
		"Failed":  0,
		"Success": 1,
	}
)

func (x ResultCodeProto) Enum() *ResultCodeProto {
	p := new(ResultCodeProto)
	*p = x
	return p
}

func (x ResultCodeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultCodeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_resultCode_proto_enumTypes[0].Descriptor()
}

func (ResultCodeProto) Type() protoreflect.EnumType {
	return &file_resultCode_proto_enumTypes[0]
}

func (x ResultCodeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultCodeProto.Descriptor instead.
func (ResultCodeProto) EnumDescriptor() ([]byte, []int) {
	return file_resultCode_proto_rawDescGZIP(), []int{0}
}

var File_resultCode_proto protoreflect.FileDescriptor

var file_resultCode_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x22, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73,
	0x65, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2a, 0x2a, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x01, 0x42, 0x30, 0x5a, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x61, 0x70, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2d, 0x67, 0x6f, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resultCode_proto_rawDescOnce sync.Once
	file_resultCode_proto_rawDescData = file_resultCode_proto_rawDesc
)

func file_resultCode_proto_rawDescGZIP() []byte {
	file_resultCode_proto_rawDescOnce.Do(func() {
		file_resultCode_proto_rawDescData = protoimpl.X.CompressGZIP(file_resultCode_proto_rawDescData)
	})
	return file_resultCode_proto_rawDescData
}

var file_resultCode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resultCode_proto_goTypes = []interface{}{
	(ResultCodeProto)(0), // 0: org.apache.seata.protocol.protobuf.ResultCodeProto
}
var file_resultCode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resultCode_proto_init() }
func file_resultCode_proto_init() {
	if File_resultCode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resultCode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resultCode_proto_goTypes,
		DependencyIndexes: file_resultCode_proto_depIdxs,
		EnumInfos:         file_resultCode_proto_enumTypes,
	}.Build()
	File_resultCode_proto = out.File
	file_resultCode_proto_rawDesc = nil
	file_resultCode_proto_goTypes = nil
	file_resultCode_proto_depIdxs = nil
}
