# test-agent Agent Configuration
# Generated on 2025-09-26 21:33:08

server:
  host: "0.0.0.0"
  port: 8080
  mode: "release"

agent:
  name: "test-agent"
  version: "1.0.0"
  description: "A default mode Go agent"

log:
  level: "info"
  format: "json"

skills:
  enabled:
    - "example"
