#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: License checker

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 18 * * *" # TimeZone: UTC 0

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect file changes
        id: changes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            changed_files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          
            if echo "$changed_files" | grep -E '\.(go|java|js|ts|py|c|cpp|h|yml|yaml|json)$|go\.(mod|sum)$|package\.json$|LICENSE|NOTICE|Dockerfile' > /dev/null; then
              echo "has-changes=true" >> $GITHUB_OUTPUT
            else
              echo "has-changes=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "has-changes=true" >> $GITHUB_OUTPUT
          fi
          
          echo "Changed files:"
          echo "$changed_files"

  license-header:
    name: License header
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Check license header
        uses: apache/skywalking-eyes@985866ce7e324454f61e22eb2db2e998db09d6f3
        with:
          log: info
          config: .licenserc.yaml
          mode: check

  dependency-license:
    name: Dependency licenses
    needs: [changes]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: needs.changes.outputs.has-changes == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Check Dependencies Licenses
        run: |
          mkdir -p ./dist-material/
          cp  ./licenses/LICENSE.tpl ./dist-material/LICENSE.tpl
          go install github.com/apache/skywalking-eyes/cmd/license-eye@47febf5
          license-eye dependency resolve --summary ./dist-material/LICENSE.tpl || exit 1
          if [ -f "./dist-material/LICENSE)" ]; then
            echo "echo LICENSE check"
            cat ./dist-material/LICENSE
          fi
      - name: Check Dependencies Licenses Invalid
        run: |
          go install github.com/apache/skywalking-eyes/cmd/license-eye@47febf5
          if [ ! -z "$(license-eye dependency check -v error | grep 'GPL\|LGPL\|ERROR')" ]; then
            echo "GPL or LGPL dependency LICENSE exists"
            license-eye dependency check -v error | grep 'GPL\|LGPL\|ERROR'
            exit 1
          fi
