// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opentrx/seata-golang/v2/pkg/tc/server (interfaces: GlobalSessionLocker)

// Package testdata is a generated GoMock package.
package testdata

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	apis "github.com/opentrx/seata-golang/v2/pkg/apis"
)

// MockGlobalSessionLocker is a mock of GlobalSessionLocker interface.
type MockGlobalSessionLocker struct {
	ctrl     *gomock.Controller
	recorder *MockGlobalSessionLockerMockRecorder
}

// MockGlobalSessionLockerMockRecorder is the mock recorder for MockGlobalSessionLocker.
type MockGlobalSessionLockerMockRecorder struct {
	mock *MockGlobalSessionLocker
}

// NewMockGlobalSessionLocker creates a new mock instance.
func NewMockGlobalSessionLocker(ctrl *gomock.Controller) *MockGlobalSessionLocker {
	mock := &MockGlobalSessionLocker{ctrl: ctrl}
	mock.recorder = &MockGlobalSessionLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlobalSessionLocker) EXPECT() *MockGlobalSessionLockerMockRecorder {
	return m.recorder
}

// TryLock mocks base method.
func (m *MockGlobalSessionLocker) TryLock(arg0 *apis.GlobalSession, arg1 time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryLock", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryLock indicates an expected call of TryLock.
func (mr *MockGlobalSessionLockerMockRecorder) TryLock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryLock", reflect.TypeOf((*MockGlobalSessionLocker)(nil).TryLock), arg0, arg1)
}

// Unlock mocks base method.
func (m *MockGlobalSessionLocker) Unlock(arg0 *apis.GlobalSession) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unlock", arg0)
}

// Unlock indicates an expected call of Unlock.
func (mr *MockGlobalSessionLockerMockRecorder) Unlock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockGlobalSessionLocker)(nil).Unlock), arg0)
}
