// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opentrx/seata-golang/v2/pkg/tc/lock (interfaces: LockManagerInterface)

// Package testdata is a generated GoMock package.
package testdata

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apis "github.com/opentrx/seata-golang/v2/pkg/apis"
	model "github.com/opentrx/seata-golang/v2/pkg/tc/model"
)

// MockLockManagerInterface is a mock of LockManagerInterface interface.
type MockLockManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLockManagerInterfaceMockRecorder
}

// MockLockManagerInterfaceMockRecorder is the mock recorder for MockLockManagerInterface.
type MockLockManagerInterfaceMockRecorder struct {
	mock *MockLockManagerInterface
}

// NewMockLockManagerInterface creates a new mock instance.
func NewMockLockManagerInterface(ctrl *gomock.Controller) *MockLockManagerInterface {
	mock := &MockLockManagerInterface{ctrl: ctrl}
	mock.recorder = &MockLockManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockManagerInterface) EXPECT() *MockLockManagerInterfaceMockRecorder {
	return m.recorder
}

// AcquireLock mocks base method.
func (m *MockLockManagerInterface) AcquireLock(arg0 *apis.BranchSession) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireLock", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AcquireLock indicates an expected call of AcquireLock.
func (mr *MockLockManagerInterfaceMockRecorder) AcquireLock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireLock", reflect.TypeOf((*MockLockManagerInterface)(nil).AcquireLock), arg0)
}

// IsLockable mocks base method.
func (m *MockLockManagerInterface) IsLockable(arg0, arg1, arg2 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLockable", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLockable indicates an expected call of IsLockable.
func (mr *MockLockManagerInterfaceMockRecorder) IsLockable(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLockable", reflect.TypeOf((*MockLockManagerInterface)(nil).IsLockable), arg0, arg1, arg2)
}

// ReleaseGlobalSessionLock mocks base method.
func (m *MockLockManagerInterface) ReleaseGlobalSessionLock(arg0 *model.GlobalTransaction) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseGlobalSessionLock", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReleaseGlobalSessionLock indicates an expected call of ReleaseGlobalSessionLock.
func (mr *MockLockManagerInterfaceMockRecorder) ReleaseGlobalSessionLock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseGlobalSessionLock", reflect.TypeOf((*MockLockManagerInterface)(nil).ReleaseGlobalSessionLock), arg0)
}

// ReleaseLock mocks base method.
func (m *MockLockManagerInterface) ReleaseLock(arg0 *apis.BranchSession) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseLock", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReleaseLock indicates an expected call of ReleaseLock.
func (mr *MockLockManagerInterfaceMockRecorder) ReleaseLock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseLock", reflect.TypeOf((*MockLockManagerInterface)(nil).ReleaseLock), arg0)
}
